### ISSUE TITLE
Affichage du logo

### ISSUE THREAD

**Issue by Narcisse** [Narcisse/ProjetIntegrateur#10]
Changer l'image affreuse de la mini-map pour le logo a étienne. Il faudra surement le faire passer dans un logiciel vectoriel comme inkscape donc j'assigne Guillaume, mais demandes de l'aide à Étienne pour inkspace vous allez voir le logiciel est super simple!

**Comment by dpx2k1** [comment]
Ok tu m'expliquera ce que tu veut j'ai download inkspace chez moi, j'ai joué avec un peu.. Je vois pas a quoi ca va servir pour le logo
