### ISSUE TITLE
Centrer le menu principal

### ISSUE THREAD

**Issue by Narcisse** [Narcisse/ProjetIntegrateur#8]
Utiliser un border layout avec un NORTH, SOUTH, EAST et WEST vide pour essayer de placer le panneau des option du menu au centre. J'assigne Loic parce que c'est son menu mais j'ai l'intention de chercher de mon bord comment le faire marcher aussi, vous pouvez tous faire de même.

**Comment by Loic-Grant-Steinhardt** [comment]
Fait
